if (self.CavalryLogger) { CavalryLogger.start_js(["lrd0k+g"]); }

__d("CometVisualCompletionConstants",[],(function(a,b,c,d,e,f){"use strict";a="data-visualcompletion";b="HeroTracing";c="InteractionTracing";d="ignore";e="ignore-dynamic";var g="ignore-late-mutation",h="loading-state",i="media-vc-image",j="css-img";f.ATTRIBUTE_NAME=a;f.HERO_TRACING_HOLD=b;f.INTERACTION_TRACING_HOLD=c;f.IGNORE=d;f.IGNORE_DYNAMIC=e;f.IGNORE_LATE_MUTATION=g;f.LOADING_STATE=h;f.MEDIA_VC_IMAGE=i;f.CSS_IMG=j}),66);
__d("CometVisualCompletionAttributes",["CometVisualCompletionConstants"],(function(a,b,c,d,e,f,g){"use strict";b={CSS_IMG:(a={},a[d("CometVisualCompletionConstants").ATTRIBUTE_NAME]=d("CometVisualCompletionConstants").CSS_IMG,a),IGNORE:(b={},b[d("CometVisualCompletionConstants").ATTRIBUTE_NAME]=d("CometVisualCompletionConstants").IGNORE,b),IGNORE_DYNAMIC:(c={},c[d("CometVisualCompletionConstants").ATTRIBUTE_NAME]=d("CometVisualCompletionConstants").IGNORE_DYNAMIC,c),IGNORE_LATE_MUTATION:(e={},e[d("CometVisualCompletionConstants").ATTRIBUTE_NAME]=d("CometVisualCompletionConstants").IGNORE_LATE_MUTATION,e),LOADING_STATE:(f={},f[d("CometVisualCompletionConstants").ATTRIBUTE_NAME]=d("CometVisualCompletionConstants").LOADING_STATE,f),MEDIA_VC_IMAGE:(a={},a[d("CometVisualCompletionConstants").ATTRIBUTE_NAME]=d("CometVisualCompletionConstants").MEDIA_VC_IMAGE,a)};g["default"]=b}),98);
__d("coerceImageishSprited",[],(function(a,b,c,d,e,f){"use strict";function a(a){if(!a||typeof a!=="object"||!a.sprited)return null;return a.sprited===1?{type:"css",className:a.spriteMapCssClass+" "+a.spriteCssClass,identifier:a.loggingID}:{type:"cssless",style:{backgroundImage:"url('"+a.spi+"')",backgroundPosition:a.p,backgroundSize:a.sz,width:a.w+"px",height:a.h+"px",backgroundRepeat:"no-repeat",display:"inline-block"},identifier:a.loggingID}}f["default"]=a}),66);
__d("coerceImageishURL",[],(function(a,b,c,d,e,f){"use strict";function a(a){if(a&&typeof a==="object"&&!a.sprited&&typeof a.uri==="string"&&a.width!==void 0&&a.height!==void 0)return a;else return null}f["default"]=a}),66);
__d("DGWRequestStreamDeferredClient",["Promise","nullthrows","requireDeferred"],(function(a,b,c,d,e,f,g){"use strict";a=function(){function a(){this.$1=null}var d=a.prototype;d.createStream=function(a,b,d,e,f){this.$2();return c("nullthrows")(this.$1).then(function(c){return c.createStream(a,b,d,e,f)})};d.$2=function(){this.$1==null&&(this.$1=new(b("Promise"))(function(a){c("requireDeferred")("DGWRequestStreamClient").__setRef("DGWRequestStreamDeferredClient").onReady(function(b){a(new b())})}))};return a}();d=new a();g["default"]=d}),98);
__d("MemoizationInstrumentation",["invariant"],(function(a,b,c,d,e,f,g,h){"use strict";var i=null;function a(a){i==null||h(0,2221),i=a}function b(a,b){return i?i.functionCall(a,b):null}g.inject=a;g.onFunctionCall=b}),98);
__d("emptyObject",[],(function(a,b,c,d,e,f){"use strict";a={};b=a;f["default"]=b}),66);
__d("memoizeWithArgs",["MemoizationInstrumentation"],(function(a,b,c,d,e,f,g){var h=Object.prototype.hasOwnProperty;function a(a,b,c){var e,f=c||a.name||"unknown";c=function(){e||(e={});var c=d("MemoizationInstrumentation").onFunctionCall("memoizeWithArgs",f),g=b.apply(void 0,arguments),i=!0;h.call(e,g)||(i=!1,e[g]=a.apply(void 0,arguments));c&&c(i);return e[g]};return c}g["default"]=a}),98);
__d("DateConsts",[],(function(a,b,c,d,e,f){var g=1e3;c=60;d=60;e=24;var h=7,i=12,j=1e3,k=30.43,l=4.333,m=365.242,n=c*d,o=n*e,p=o*h,q=o*m,r=g*c,s=r*d,t=g*o,u=t*h,v=t*m,w={SUNDAY:0,MONDAY:1,TUESDAY:2,WEDNESDAY:3,THURSDAY:4,FRIDAY:5,SATURDAY:6};Object.freeze(w);function a(a,b){return new Date(a,b,0).getDate()}function b(){return Date.now()/g}var x={instantRange:{since:-864e10,until:864e10+1}};f.MS_PER_SEC=g;f.SEC_PER_MIN=c;f.MIN_PER_HOUR=d;f.HOUR_PER_DAY=e;f.DAYS_PER_WEEK=h;f.MONTHS_PER_YEAR=i;f.US_PER_MS=j;f.AVG_DAYS_PER_MONTH=k;f.AVG_WEEKS_PER_MONTH=l;f.AVG_DAYS_PER_YEAR=m;f.SEC_PER_HOUR=n;f.SEC_PER_DAY=o;f.SEC_PER_WEEK=p;f.SEC_PER_YEAR=q;f.MS_PER_MIN=r;f.MS_PER_HOUR=s;f.MS_PER_DAY=t;f.MS_PER_WEEK=u;f.MS_PER_YEAR=v;f.DAYS=w;f.getDaysInMonth=a;f.getCurrentTimeInSeconds=b;f["private"]=x}),66);
__d("isClickIDBlacklistSVDomainURI",["ClickIDDomainBlacklistSVConfig"],(function(a,b,c,d,e,f){"use strict";var g=["http","https"];function a(a){return!g.includes(a.getProtocol())?!1:b("ClickIDDomainBlacklistSVConfig").domains.some(function(b){if(a.isSubdomainOfDomain(b))return!0;if(!b.includes(".")){var c=a.getDomain().split(".");return c.includes(b)}return!1})}e.exports=a}),null);
__d("isFacebookSVDomainURI",["FBDomainsSVConfig"],(function(a,b,c,d,e,f){"use strict";var g=["http","https"];function a(a){if(g.indexOf(a.getProtocol())===-1)return!1;a=b("FBDomainsSVConfig").domains.get(a.getDomain());return a!=null}e.exports=a}),null);
__d("isFbDotComURI",[],(function(a,b,c,d,e,f){var g=new RegExp("(^|\\.)fb\\.com?$","i"),h=["http","https"];function a(a){if(a.isEmpty()&&a.toString()!=="#")return!1;return!a.getDomain()&&!a.getProtocol()?!1:h.indexOf(a.getProtocol())!==-1&&g.test(a.getDomain())}f["default"]=a}),66);
__d("asset",[],(function(a,b,c,d,e,f){function a(){for(var a=arguments.length,b=new Array(a),c=0;c<a;c++)b[c]=arguments[c];throw new Error("asset("+b.join(",")+"): Unexpected asset reference")}e.exports=a}),null);
__d("expectationViolation",["ErrorNormalizeUtils","FBLogger","cr:840411","emptyFunction","sprintf"],(function(a,b,c,d,e,f,g){"use strict";d=c("emptyFunction");function a(a){var b;for(var d=arguments.length,e=new Array(d>1?d-1:0),f=1;f<d;f++)e[f-1]=arguments[f];(b=c("FBLogger")("expectation_violation").blameToPreviousFrame()).warn.apply(b,[a].concat(e))}a.setHandler=b;function b(a){d=a}g["default"]=a}),98);